server:
  port: 8088

mybatis:
  type-aliases-package: com.gsd.**.domain
  mapper-locations: classpath*:mapper/**/*Mapper.xml
spring:
  profiles:
    active: druid
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 10s
    database: 0


token:
  header: Authorization
  secret: gdsfdsagdsafadsf
  expireTime: 10

